-- BASE DE DATOS E-SPORTS
-- ALBERTO GARCÍA NAVARRO 1ºCFGS DAW

-- TABLA 'COMPETICIONES' QUE CONTIENE LOS DATOS DE LAS COMPETICIONES, PREMIOS, EQUIPOS, TIPO DE VIDEOJUEGO.
CREATE TABLE COMPETICIONES (
    COD_COMPETICION NUMBER(5) CONSTRAINT COM_COD_PK PRIMARY KEY,
    NOMBRE_COMPETICION VARCHAR2(20) NOT NULL CONSTRAINT COM_NOM_UK UNIQUE,
    PREMIO_PRIMERO NUMBER(5) CONSTRAINT COM_PRE_NN NOT NULL,
    PREMIO_SEGUNDO NUMBER(5),
    PREMIO_TERCERO NUMBER(5),
    MAX_EQUIPOS NUMBER(3) CONSTRAINT COM_MAX_NN NOT NULL
);

-- TABLA 'EQUIPOS' QUE CONTIENE LOS DATOS DE LOS EQUIPOS QUE JUEGAN PARTIDOS EN COMPETICIONES.
CREATE TABLE EQUIPOS (
    COD_EQUIPO NUMBER(5) CONSTRAINT EQU_COD_PK PRIMARY KEY, 
    NOMBRE_EQUIPO VARCHAR2(20) NOT NULL CONSTRAINT EQU_NOM_UK UNIQUE,
    FECHA_CREACION DATE
);

-- TABLA 'JUGADORES' QUE CONTIENE LOS DATOS DE LOS JUGADORES QUE EXISTEN, ESTOS PUEDEN PERTENECER O NO A EQUIPOS.
CREATE TABLE JUGADORES (
    DNI VARCHAR2(9) CONSTRAINT JUG_DNI_PK PRIMARY KEY,
    NICK VARCHAR2(20) NOT NULL CONSTRAINT JUG_NIC_UK UNIQUE,
    NOMBRE_JUGADOR VARCHAR2(20) CONSTRAINT JUG_NOM_NN NOT NULL,
    APELLIDO1 VARCHAR2(20) CONSTRAINT JUG_APE_NN NOT NULL,
    APELLIDO2 VARCHAR2(20),
    DIRECCION VARCHAR2(35),
    FECHA_NACIMIENTO DATE,
    -- NO PONDREMOS 'NOT NULL' PORQUE PUEDE HABER JUGADORES SIN EQUIPOS.
    COD_EQUIPO NUMBER(5) CONSTRAINT JUG_COD_FK REFERENCES EQUIPOS
);

-- TABLA 'PARTIDOS' QUE RELACIONA LAS COMPETICIONES CON LOS EQUIPOS QUE JUEGAN PARTIDOS.
CREATE TABLE PARTIDOS (
    COD_PARTIDO NUMBER(5) CONSTRAINT PAR_COD_PK PRIMARY KEY,
    COD_COMPETICION NUMBER(5) CONSTRAINT PAR_COM_FK REFERENCES COMPETICIONES,
    COD_EQUIPO1 NUMBER(5) CONSTRAINT PAR_EQ1_FK REFERENCES EQUIPOS,
    COD_EQUIPO2 NUMBER(5) CONSTRAINT PAR_EQ2_FK REFERENCES EQUIPOS,
    RESULTADO NUMBER (5),
    -- EL RESULTADO SE MARCARÁ CON EL CÓDIGO DEL EQUIPO QUE GANE
    CONSTRAINT PAR_RES_CK CHECK (RESULTADO IN(COD_EQUIPO1, COD_EQUIPO2))
);

-- CREAMOS UNA TABLA ADICIONAL 'RANKING' QUE LA USAREMOS PARA NUESTRO PROGRAMA, DONDE SE IRÁ CONTANDO LAS VICTORIAS
CREATE TABLE RANKING (
    COD_EQUIPO NUMBER(5) CONSTRAINT RAN_EQU_FK REFERENCES EQUIPOS,
    VICTORIAS NUMBER(3)
);

-- INSERTAMOS DATOS EN LAS TABLAS, SALVO 'PARTIDOS' QUE SE GENERARÁN DE FORMA AUTOMÁTICA
INSERT INTO COMPETICIONES VALUES (001, 'RPL MASTER RIFT', '500', '100', '', 8);

INSERT INTO EQUIPOS VALUES (001, 'NOV4 QUABU', '10/11/2019');
INSERT INTO EQUIPOS VALUES (002, 'INMOLATE IN MID', '09/12/2017');
INSERT INTO EQUIPOS VALUES (003, 'FALLENWARRIORS', '05/06/2021');
INSERT INTO EQUIPOS VALUES (004, 'RECREATIVO THUNDER', '10/10/2018');
INSERT INTO EQUIPOS VALUES (005, 'MIGHTY MEERKATS', '03/12/2020');
INSERT INTO EQUIPOS VALUES (006, 'MSES ONE', '');
INSERT INTO EQUIPOS VALUES (007, 'FARMERS BRIGADE', '02/08/2019');
INSERT INTO EQUIPOS VALUES (008, 'CYCLON GAMING', '');

INSERT INTO JUGADORES VALUES ('97334939C', 'DAKOR', 'MANUEL', 'FERNÁNDEZ', 'GARCÍA', '', '10/11/1998', 001);
INSERT INTO JUGADORES VALUES ('16918468J', 'KALAMEET', 'VÍCTOR', 'MÉNDEZ', '', 'C/TAMBOR 7, MADRID', '15/08/2001', 001);
INSERT INTO JUGADORES VALUES ('37837643K', 'SAVIOR', 'SARA', 'GARCÍA', 'LÓPEZ', '', '', 001);
INSERT INTO JUGADORES VALUES ('58822322Y', 'MAKITAH', 'JAVIER', 'LÓPEZ', 'DOMÍNGUEZ', 'C/ALEGRÍA 8, RONDA', '23/10/2001', 002);
INSERT INTO JUGADORES VALUES ('58279008K', 'JUST HARU', 'JULIO', 'NAVARRO', 'RIVERA', '', '', 002);
INSERT INTO JUGADORES VALUES ('22896751K', 'OLAF ADVENTURE', 'MARCOS', 'RODRÍGUEZ', 'DELGADO', 'AV/LAS PALMAS, SEVILLA', '', 002);
INSERT INTO JUGADORES VALUES ('28762411Z', 'ESKIPER', 'ÁLVARO', 'GRACIA', '', '', '', 003);
INSERT INTO JUGADORES VALUES ('92989509A', 'CODOR', 'MANUEL', 'DELGADO', 'PÉREZ', '', '12/10/1995', 003);
INSERT INTO JUGADORES VALUES ('95858712W', 'SAMMUTIFU', 'SAMUEL', 'GÓMEZ', 'CONTRERAS', '', '', 003);
INSERT INTO JUGADORES VALUES ('43113720J', 'GEGOR', 'JORGE', 'RIVERA', '', '', '10/11/1998', 004);
INSERT INTO JUGADORES VALUES ('56886844R', 'BLOODY', 'LUCÍA', 'NAVARRO', 'GARCÍA', 'C/RONDA 18, MÁLAGA', '10/11/1996', 004);
INSERT INTO JUGADORES VALUES ('24510017K', 'CLAWWP', 'CARLOS', 'CONTRERAS', '', '', '', 004);
INSERT INTO JUGADORES VALUES ('69853423P', 'CROWN', 'PEDRO', 'GARRIDO', 'ALEO', '', '', 005);
INSERT INTO JUGADORES VALUES ('08167978B', 'EMVIPI1', 'ELENA', 'CASTRO', '', 'AV/MONTELLANO 7, BADAJOZ', '23/10/2003', 005);
INSERT INTO JUGADORES VALUES ('78847749T', 'PATITOCUACK', 'ALBERTO', 'GÓMEZ', 'RIVERA', '', '09/11/1995', 005);
INSERT INTO JUGADORES VALUES ('79108055S', 'PONCHIXD', 'JAIME', 'BARBERO', '', '', '', 006);
INSERT INTO JUGADORES VALUES ('37698354C', 'EUZER', 'RODRIGO', 'BLANCO', 'DELGADO', '', '', 006);
INSERT INTO JUGADORES VALUES ('68313237V', 'XAVINETA', 'XAVIER', 'ALEO', '', 'C/LA LIBERTAD 43, BARCELONA', '', 006);
INSERT INTO JUGADORES VALUES ('18888428T', 'MUFASHAK', 'ROBERTO', 'PÉREZ', 'LÓPEZ', '', '', 007);
INSERT INTO JUGADORES VALUES ('99127624Q', 'ESCU22', 'JUAN', 'FERNÁNDEZ', '', '', '10/12/1999', 007);
INSERT INTO JUGADORES VALUES ('67152510P', 'NAUTILUS', 'NATALIA', 'MONTADO', 'MONTERO', 'AV/PÍO XII 31, VALENCIA', '', 007);
INSERT INTO JUGADORES VALUES ('61766115Y', 'TAVII', 'TOM', 'MONCADA', '', '', '05/07/1994', 008);
INSERT INTO JUGADORES VALUES ('65191777W', 'MIGO', 'ARMANDO', 'RODRIGUEZ', 'NAVARRO', '', '01/12/2002', 008);
INSERT INTO JUGADORES VALUES ('31612495F', 'KARMA', 'JUAN LUIS', 'DELGADO', 'ROJAS', 'C/CUESTA DEL ROSARIO 18, CÁDIZ', '06/06/1993', 008);